Senai/Models/Turmas.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;

namespace Senai.Models
{
    [Table("Turmas")]
    public class Turmas
    {
        [Key]
        public int id { get; set; }
        [MaxLength(100)]
        public string nome_turma { get; set; }
        public ICollection<Atividades> Atividades { get; set; }
    }
}

Senai/Controllers/AtividadesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Senai.Data;
using Senai.Models;

namespace Senai.Controllers
{
    public class AtividadesController : Controller
    {
        private readonly SenaiContext _context;

        public AtividadesController(SenaiContext context)
        {
            _context = context;
        }

        // GET: Atividades
        public async Task<IActionResult> Index()
        {
            var senaiContext = _context.Atividades.Include(a => a.Turma);
            return View(await senaiContext.ToListAsync());
        }

        // GET: Atividades/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Atividades == null)
            {
                return NotFound();
            }

            var atividades = await _context.Atividades
                .Include(a => a.Turma)
                .FirstOrDefaultAsync(m => m.id == id);
            if (atividades == null)
            {
                return NotFound();
            }

            return View(atividades);
        }

        // GET: Atividades/Create
        public IActionResult Create()
        {
            ViewData["id_turma"] = new SelectList(_context.Turmas, "id", "nome_turma");
            return View();
        }

        // POST: Atividades/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("nome,id_turma")] Atividades atividades)
        {
            //var errors = ModelState.Values.SelectMany(v => v.Errors);
            //foreach (var error in errors)
            //{
            //    Console.WriteLine(error.ErrorMessage);
            //    var idTurmaSelecionada = atividades.id_turma;
            //}
            if (ModelState.IsValid)
            {
                
                _context.Add(atividades);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["id_turma"] = new SelectList(_context.Turmas, "id", "nome_turma", atividades.id_turma);
            return View(atividades);
        }

        // GET: Atividades/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Atividades == null)
            {
                return NotFound();
            }

            var atividades = await _context.Atividades.FindAsync(id);
            if (atividades == null)
            {
                return NotFound();
            }
            ViewData["id_turma"] = new SelectList(_context.Turmas, "id", "nome_turma", atividades.id_turma);
            return View(atividades);
        }

        // POST: Atividades/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("nome,id_turma")] Atividades atividades)
        {
            if (id != atividades.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(atividades);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AtividadesExists(atividades.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["id_turma"] = new SelectList(_context.Turmas, "id", "nome_turma", atividades.id_turma);
            return View(atividades);
        }

        // GET: Atividades/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Atividades == null)
            {
                return NotFound();
            }

            var atividades = await _context.Atividades
                .Include(a => a.Turma)
                .FirstOrDefaultAsync(m => m.id == id);
            if (atividades == null)
            {
                return NotFound();
            }

            return View(atividades);
        }

        // POST: Atividades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Atividades == null)
            {
                return Problem("Entity set 'SenaiContext.Atividades'  is null.");
            }
            var atividades = await _context.Atividades.FindAsync(id);
            if (atividades != null)
            {
                _context.Atividades.Remove(atividades);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AtividadesExists(int id)
        {
          return (_context.Atividades?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

Senai/Controllers/TurmasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Senai.Data;
using Senai.Models;

namespace Senai.Controllers
{
    public class TurmasController : Controller
    {
        private readonly SenaiContext _context;

        public TurmasController(SenaiContext context)
        {
            _context = context;
        }

        // GET: Turmas
        public async Task<IActionResult> Index()
        {
              return _context.Turmas != null ? 
                          View(await _context.Turmas.ToListAsync()) :
                          Problem("Entity set 'SenaiContext.Turmas'  is null.");
        }

        // GET: Turmas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Turmas == null)
            {
                return NotFound();
            }

            var turmas = await _context.Turmas
                .FirstOrDefaultAsync(m => m.id == id);
            if (turmas == null)
            {
                return NotFound();
            }

            return View(turmas);
        }

        // GET: Turmas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Turmas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nome_turma")] Turmas turmas)
        {
            if (ModelState.IsValid)
            {
                _context.Add(turmas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(turmas);
        }

        // GET: Turmas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Turmas == null)
            {
                return NotFound();
            }

            var turmas = await _context.Turmas.FindAsync(id);
            if (turmas == null)
            {
                return NotFound();
            }
            return View(turmas);
        }

        // POST: Turmas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nome_turma")] Turmas turmas)
        {
            if (id != turmas.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(turmas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TurmasExists(turmas.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(turmas);
        }

        // GET: Turmas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Turmas == null)
            {
                return NotFound();
            }

            var turmas = await _context.Turmas
                .FirstOrDefaultAsync(m => m.id == id);
            if (turmas == null)
            {
                return NotFound();
            }

            return View(turmas);
        }

        // POST: Turmas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Turmas == null)
            {
                return Problem("Entity set 'SenaiContext.Turmas'  is null.");
            }
            var turmas = await _context.Turmas.FindAsync(id);
            if (turmas != null)
            {
                _context.Turmas.Remove(turmas);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TurmasExists(int id)
        {
          return (_context.Turmas?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

Senai/Views/Turmas/Create.cshtml
@model Senai.Models.Turmas

@{
    ViewData["Title"] = "Create";
}

<h1>Criar</h1>

<h4>Turmas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nome_turma" class="control-label"></label>
                <input asp-for="nome_turma" class="form-control" />
                <span asp-validation-for="nome_turma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Senai/Views/Turmas/Delete.cshtml
@model Senai.Models.Turmas

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Turmas</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nome_turma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nome_turma)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Senai/Views/Turmas/Details.cshtml
@model Senai.Models.Turmas

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Turmas</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nome_turma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nome_turma)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Senai/Views/Turmas/Edit.cshtml
@model Senai.Models.Turmas

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Turmas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="nome_turma" class="control-label"></label>
                <input asp-for="nome_turma" class="form-control" />
                <span asp-validation-for="nome_turma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Senai/Views/Turmas/Index.cshtml
@model IEnumerable<Senai.Models.Turmas>

@{
    ViewData["Title"] = "Index";
}

<h1>Turmas</h1>

<p>
    <a asp-action="Create">Adicionar turma</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nome_turma)
            </th>
            <td>
                <a asp-controller="Atividades" asp-action="Index">Atividades</a>
            </td>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nome_turma)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>